version: 2.0
jobs:
  build:
    docker:
      - image: membrane/bionic-membrane:latest
    environment:
      MIX_ENV: test
    working_directory: '~/app'

    steps:
      - checkout
      - run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test


